<div class="space-y-4">

    {{-- Page title --}}
    <div>
        <h1 class="font-bold text-fg text-xl">Password</h1>
        <p class="mt-0.5 text-zinc-500 text-sm">Keep your account secure with a strong, unique password.</p>
    </div>

    <form wire:submit.prevent="changePassword" class="space-y-4">

        {{-- Change Password --}}
        <div class="bg-surface border border-surface rounded-xl overflow-hidden">
            <div class="px-6 py-4 border-surface border-b">
                <h2 class="font-semibold text-fg text-sm">Change Password</h2>
                <p class="mt-0.5 text-zinc-500 text-xs">We recommend using a password generated by your browser.</p>
            </div>
            <div class="space-y-4 px-6 py-5">

                <div>
                    <label class="block mb-1.5 font-medium text-zinc-400 text-xs">Current Password</label>
                    <input type="password" wire:model.defer="current_password" placeholder="Your current password"
                        class="bg-surface-2/70 px-3 py-2.5 border border-surface-2/60 focus:border-zinc-500 rounded-lg focus:outline-none w-full text-fg text-sm transition placeholder-fg-muted">
                    @error('current_password')
                        <p class="mt-1.5 text-red-400 text-xs">{{ $message }}</p>
                    @enderror
                </div>

                <div>
                    <label class="block mb-1.5 font-medium text-zinc-400 text-xs">New Password</label>
                    <input type="password" wire:model.defer="password" placeholder="Your new password"
                        class="bg-surface-2/70 px-3 py-2.5 border border-surface-2/60 focus:border-zinc-500 rounded-lg focus:outline-none w-full text-fg text-sm transition placeholder-fg-muted">
                    @error('password')
                        <p class="mt-1.5 text-red-400 text-xs">{{ $message }}</p>
                    @enderror
                    <p class="mt-1.5 text-zinc-500 text-xs">Must be 8–20 characters, including numbers and mixed case
                        letters.</p>
                </div>

                <div>
                    <label class="block mb-1.5 font-medium text-zinc-400 text-xs">Confirm New Password</label>
                    <input type="password" wire:model.defer="password_confirmation"
                        placeholder="Your new password again"
                        class="bg-surface-2/70 px-3 py-2.5 border border-surface-2/60 focus:border-zinc-500 rounded-lg focus:outline-none w-full text-fg text-sm transition placeholder-fg-muted">
                </div>

            </div>
        </div>

        {{-- Save bar --}}
        <div class="flex justify-end items-center py-1">
            <button type="submit"
                class="bg-indigo-600 hover:bg-indigo-500 px-5 py-2 rounded-lg font-medium text-white text-sm transition">
                Update password
            </button>
        </div>

    </form>

</div>
