<div class="max-w-4xl">

    <form wire:submit.prevent="changePassword">

        <h1 class="text-2xl font-semibold text-white mb-1">
            Password
        </h1>

        <p class="text-sm text-neutral-400 mb-10">
            Keep your account secure with a complex password. We recommend passwords
            automatically generated by your browser when possible.
        </p>

        {{-- PASSWORD --}}
        <div class="grid grid-cols-1 md:grid-cols-2 gap-10 mb-12">
            <div>
                <h3 class="text-lg font-semibold text-white mb-1">Password</h3>
                <p class="text-sm text-neutral-400">
                    Update your account password.
                </p>
            </div>

            <div class="space-y-5">

                {{-- Current Password --}}
                <div>
                    <label class="block text-sm text-neutral-400 mb-1">
                        Password
                    </label>
                    <input
                        type="password"
                        wire:model.defer="current_password"
                        placeholder="Your current password"
                        class="w-full rounded-lg bg-neutral-950 border border-neutral-800
                               px-3 py-2 text-white focus:border-indigo-500 focus:outline-none">
                    @error('current_password')
                        <span class="text-red-500 text-sm">{{ $message }}</span>
                    @enderror
                </div>

                {{-- New Password --}}
                <div>
                    <label class="block text-sm text-neutral-400 mb-1">
                        New Password
                    </label>
                    <input
                        type="password"
                        wire:model.defer="password"
                        placeholder="Your new password"
                        class="w-full rounded-lg bg-neutral-950 border border-neutral-800
                               px-3 py-2 text-white focus:border-indigo-500 focus:outline-none">
                    @error('password')
                        <span class="text-red-500 text-sm">{{ $message }}</span>
                    @enderror

                    <p class="text-xs text-neutral-400 mt-2">
                        Passwords must be 8–20 characters, and include numbers and mixed case letters.
                    </p>
                </div>

                {{-- Confirm Password --}}
                <div>
                    <label class="block text-sm text-neutral-400 mb-1">
                        New Password Confirmation
                    </label>
                    <input
                        type="password"
                        wire:model.defer="password_confirmation"
                        placeholder="Your new password again"
                        class="w-full rounded-lg bg-neutral-950 border border-neutral-800
                               px-3 py-2 text-white focus:border-indigo-500 focus:outline-none">
                </div>

            </div>
        </div>

        <div class="flex items-center justify-end gap-4">
            <button
                type="submit"
                class="px-6 py-2 rounded-lg bg-indigo-600 hover:bg-indigo-500
                       text-white font-medium transition"
            >
                Save
            </button>
        </div>

    </form>
</div>
