flowchart TD
    Dialer["Dialer Modules"]
    Dialer --> Campaign["Campaign"]
    Dialer --> Inbound["Inbound"]
    Dialer --> Operations["Operations"]
    Dialer --> Workforce["Workforce"]
    Dialer --> AccessControl["Access Control"]
    Dialer --> Administration["Administration"]

    Campaign --> CampaignMod["Campaign"]
    Campaign --> CallLists["Call Lists"]
    Campaign --> Dispositions["Dispositions"]

    Inbound --> InGroups["In-Groups"]
    Inbound --> DIDs["DIDs"]
    Inbound --> IvrMenus["IVR Menus"]

    Operations --> Activitylogs["Activity Logs"]
    Operations --> Agent["Agent"]
    Operations --> Leads["Leads"]
    Operations --> Stores["Stores"]

    AccessControl --> Auth["Auth"]
    AccessControl --> Permissions["Permissions"]
    AccessControl --> Roles["Roles"]

    Administration --> Settings["Settings"]
    Administration --> UserGroups["User Groups"]
    Administration --> Users["Users"]