flowchart TD
    Dialer["Dialer Modules"]
    Dialer --> Inbound["Inbound"]
    Dialer --> Activitylogs["Activity Logs"]
    Dialer --> Agent["Agent"]
    Dialer --> Auth["Auth"]
    Dialer --> Campaign["Campaign"]
    Dialer --> Leads["Leads"]
    Dialer --> Permissions["Permissions"]
    Dialer --> Roles["Roles"]
    Dialer --> Settings["Settings"]
    Dialer --> Stores["Stores"]
    Dialer --> UserGroups["User Groups"]
    Dialer --> Users["Users"]

    Inbound --> InGroups["In-Groups"]
    Inbound --> DIDs["DIDs"]
    Inbound --> IvrMenus["IVR Menus"]